Use Rust edition 2018
simon-frankau/galette pull request #2
Opened 2020-12-16 22:01 UTC by rfuest

I stumbled upon your repo while I was searching for a tool to program GALs. After doing some successful tests I noticed that the project didn't use edition 2018 yet and I decided to change that.

The PR is a bit noisy because I did run rustfmt, but I hope that's OK. I did add some `rustfmt::skip` attributes in `gal.rs` to make sure the formatting of the pin lists stays consistent with the format used in the `pld` input files.

I did also change the file checksum code to use an `u16` to match the JEDEC standard. While I don't have a program that verifies the checksum in a JEDEC file, I was able to compare the overflow behavior with a large file generated by ispLEVER and the checksums were identical after the change to `u16`.

2020-12-20 21:06 UTC, simon-frankau requested changes
Oh, wow. Thanks! This project is my attempt to learn Rust, so the changes you're suggesting are all helpful to me in learning it, and it's great to see someone interested enough to fix the code up. :)

I have a couple of quick comments, but if you're too busy to answer them I'm happy to merge and fix up later.

Cheers!

2020-12-20 21:06 UTC, simon-frankau commented on src/writer.rs
> +        assert_eq!(file_checksum(input), 0x00FF);
When I run this locally, this test fails. `wrapping_add` adds modulo 65536, the standard says to add modulo 65535, and galasm seems to add modulo 65536. If ispLEVER uses 65536, I guess we can be consistent with other tools, rather than the standard?

2020-12-20 21:46 UTC, rfuest commented on src/gal_builder.rs
>          }
You are right, I didn't catch that. I've fixed the problem and added a few tests to make sure it behaves the same way as before.

2020-12-20 22:03 UTC, rfuest commented on src/writer.rs
> +        assert_eq!(file_checksum(input), 0x00FF);
I must have missed to commit the latest changes to this test, it was supposed to check for `0x00FE`.

After checking some more JEDEC files I'm pretty confident that the modulo 65535 in the standard is an error. Other programs like ispLEVER or PALASM4 do seem to use a simple 16 bit sum.

2020-12-27 22:09 UTC, simon-frankau commented on src/gal_builder.rs
>          }
Thanks, looks good to me.

2020-12-27 22:09 UTC, simon-frankau commented on src/writer.rs
> +        assert_eq!(file_checksum(input), 0x00FF);
Thanks.

2020-12-27 22:10 UTC, simon-frankau approved these changes

2020-12-27 22:10 UTC, merged

2020-12-27 22:13 UTC, simon-frankau commented
Thanks so much. Sorry for the delay - Christmas has been a bit busy - but I really appreciate your contribution. Happy New Year!